#!/bin/sh
# Build the EN preprint PDF from markdown + figures/.
# Requires: pandoc, xelatex (texlive-xetex), DejaVu Serif font.
# Figures are generated by figures/make_figs.py (matplotlib).
cd "$(dirname "$0")"
pandoc preprint-draft.md -o preprint-draft.pdf \
  --pdf-engine=xelatex --toc \
  -V geometry:margin=2.2cm -V fontsize=10pt -V mainfont="DejaVu Serif" -V colorlinks=true \
  -H _pandoc-header-preprint.tex
echo "wrote preprint-draft.pdf"
